server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asset_registry
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    # V1__init.sql будет добавлен на Шаге 2
